/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QueueDisplayRouteImport } from './routes/queue-display'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPharmacyRouteImport } from './routes/app.pharmacy'
import { Route as AppLabRouteImport } from './routes/app.lab'
import { Route as AppHrRouteImport } from './routes/app.hr'
import { Route as AppFrontOfficeRouteImport } from './routes/app.front-office'
import { Route as AppDoctorRouteImport } from './routes/app.doctor'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as PrintTokenVisitIdRouteImport } from './routes/print.token.$visitId'
import { Route as PrintResultSampleIdRouteImport } from './routes/print.result.$sampleId'
import { Route as PrintOpSlipVisitIdRouteImport } from './routes/print.op-slip.$visitId'
import { Route as PrintLabelOrderIdRouteImport } from './routes/print.label.$orderId'
import { Route as PrintBillIdRouteImport } from './routes/print.bill.$id'

const QueueDisplayRoute = QueueDisplayRouteImport.update({
  id: '/queue-display',
  path: '/queue-display',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPharmacyRoute = AppPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AppRoute,
} as any)
const AppLabRoute = AppLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRoute = AppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AppRoute,
} as any)
const AppFrontOfficeRoute = AppFrontOfficeRouteImport.update({
  id: '/front-office',
  path: '/front-office',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorRoute = AppDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const PrintTokenVisitIdRoute = PrintTokenVisitIdRouteImport.update({
  id: '/print/token/$visitId',
  path: '/print/token/$visitId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintResultSampleIdRoute = PrintResultSampleIdRouteImport.update({
  id: '/print/result/$sampleId',
  path: '/print/result/$sampleId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintOpSlipVisitIdRoute = PrintOpSlipVisitIdRouteImport.update({
  id: '/print/op-slip/$visitId',
  path: '/print/op-slip/$visitId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintLabelOrderIdRoute = PrintLabelOrderIdRouteImport.update({
  id: '/print/label/$orderId',
  path: '/print/label/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintBillIdRoute = PrintBillIdRouteImport.update({
  id: '/print/bill/$id',
  path: '/print/bill/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/queue-display': typeof QueueDisplayRoute
  '/app/admin': typeof AppAdminRoute
  '/app/doctor': typeof AppDoctorRoute
  '/app/front-office': typeof AppFrontOfficeRoute
  '/app/hr': typeof AppHrRoute
  '/app/lab': typeof AppLabRoute
  '/app/pharmacy': typeof AppPharmacyRoute
  '/print/bill/$id': typeof PrintBillIdRoute
  '/print/label/$orderId': typeof PrintLabelOrderIdRoute
  '/print/op-slip/$visitId': typeof PrintOpSlipVisitIdRoute
  '/print/result/$sampleId': typeof PrintResultSampleIdRoute
  '/print/token/$visitId': typeof PrintTokenVisitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/queue-display': typeof QueueDisplayRoute
  '/app/admin': typeof AppAdminRoute
  '/app/doctor': typeof AppDoctorRoute
  '/app/front-office': typeof AppFrontOfficeRoute
  '/app/hr': typeof AppHrRoute
  '/app/lab': typeof AppLabRoute
  '/app/pharmacy': typeof AppPharmacyRoute
  '/print/bill/$id': typeof PrintBillIdRoute
  '/print/label/$orderId': typeof PrintLabelOrderIdRoute
  '/print/op-slip/$visitId': typeof PrintOpSlipVisitIdRoute
  '/print/result/$sampleId': typeof PrintResultSampleIdRoute
  '/print/token/$visitId': typeof PrintTokenVisitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/queue-display': typeof QueueDisplayRoute
  '/app/admin': typeof AppAdminRoute
  '/app/doctor': typeof AppDoctorRoute
  '/app/front-office': typeof AppFrontOfficeRoute
  '/app/hr': typeof AppHrRoute
  '/app/lab': typeof AppLabRoute
  '/app/pharmacy': typeof AppPharmacyRoute
  '/print/bill/$id': typeof PrintBillIdRoute
  '/print/label/$orderId': typeof PrintLabelOrderIdRoute
  '/print/op-slip/$visitId': typeof PrintOpSlipVisitIdRoute
  '/print/result/$sampleId': typeof PrintResultSampleIdRoute
  '/print/token/$visitId': typeof PrintTokenVisitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/queue-display'
    | '/app/admin'
    | '/app/doctor'
    | '/app/front-office'
    | '/app/hr'
    | '/app/lab'
    | '/app/pharmacy'
    | '/print/bill/$id'
    | '/print/label/$orderId'
    | '/print/op-slip/$visitId'
    | '/print/result/$sampleId'
    | '/print/token/$visitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/queue-display'
    | '/app/admin'
    | '/app/doctor'
    | '/app/front-office'
    | '/app/hr'
    | '/app/lab'
    | '/app/pharmacy'
    | '/print/bill/$id'
    | '/print/label/$orderId'
    | '/print/op-slip/$visitId'
    | '/print/result/$sampleId'
    | '/print/token/$visitId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/queue-display'
    | '/app/admin'
    | '/app/doctor'
    | '/app/front-office'
    | '/app/hr'
    | '/app/lab'
    | '/app/pharmacy'
    | '/print/bill/$id'
    | '/print/label/$orderId'
    | '/print/op-slip/$visitId'
    | '/print/result/$sampleId'
    | '/print/token/$visitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  QueueDisplayRoute: typeof QueueDisplayRoute
  PrintBillIdRoute: typeof PrintBillIdRoute
  PrintLabelOrderIdRoute: typeof PrintLabelOrderIdRoute
  PrintOpSlipVisitIdRoute: typeof PrintOpSlipVisitIdRoute
  PrintResultSampleIdRoute: typeof PrintResultSampleIdRoute
  PrintTokenVisitIdRoute: typeof PrintTokenVisitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/queue-display': {
      id: '/queue-display'
      path: '/queue-display'
      fullPath: '/queue-display'
      preLoaderRoute: typeof QueueDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pharmacy': {
      id: '/app/pharmacy'
      path: '/pharmacy'
      fullPath: '/app/pharmacy'
      preLoaderRoute: typeof AppPharmacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lab': {
      id: '/app/lab'
      path: '/lab'
      fullPath: '/app/lab'
      preLoaderRoute: typeof AppLabRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hr': {
      id: '/app/hr'
      path: '/hr'
      fullPath: '/app/hr'
      preLoaderRoute: typeof AppHrRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/front-office': {
      id: '/app/front-office'
      path: '/front-office'
      fullPath: '/app/front-office'
      preLoaderRoute: typeof AppFrontOfficeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/doctor': {
      id: '/app/doctor'
      path: '/doctor'
      fullPath: '/app/doctor'
      preLoaderRoute: typeof AppDoctorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/print/token/$visitId': {
      id: '/print/token/$visitId'
      path: '/print/token/$visitId'
      fullPath: '/print/token/$visitId'
      preLoaderRoute: typeof PrintTokenVisitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/result/$sampleId': {
      id: '/print/result/$sampleId'
      path: '/print/result/$sampleId'
      fullPath: '/print/result/$sampleId'
      preLoaderRoute: typeof PrintResultSampleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/op-slip/$visitId': {
      id: '/print/op-slip/$visitId'
      path: '/print/op-slip/$visitId'
      fullPath: '/print/op-slip/$visitId'
      preLoaderRoute: typeof PrintOpSlipVisitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/label/$orderId': {
      id: '/print/label/$orderId'
      path: '/print/label/$orderId'
      fullPath: '/print/label/$orderId'
      preLoaderRoute: typeof PrintLabelOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/bill/$id': {
      id: '/print/bill/$id'
      path: '/print/bill/$id'
      fullPath: '/print/bill/$id'
      preLoaderRoute: typeof PrintBillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppDoctorRoute: typeof AppDoctorRoute
  AppFrontOfficeRoute: typeof AppFrontOfficeRoute
  AppHrRoute: typeof AppHrRoute
  AppLabRoute: typeof AppLabRoute
  AppPharmacyRoute: typeof AppPharmacyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppDoctorRoute: AppDoctorRoute,
  AppFrontOfficeRoute: AppFrontOfficeRoute,
  AppHrRoute: AppHrRoute,
  AppLabRoute: AppLabRoute,
  AppPharmacyRoute: AppPharmacyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  QueueDisplayRoute: QueueDisplayRoute,
  PrintBillIdRoute: PrintBillIdRoute,
  PrintLabelOrderIdRoute: PrintLabelOrderIdRoute,
  PrintOpSlipVisitIdRoute: PrintOpSlipVisitIdRoute,
  PrintResultSampleIdRoute: PrintResultSampleIdRoute,
  PrintTokenVisitIdRoute: PrintTokenVisitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
